Backwards Compatible Generic Modules
avaje/avaje-inject pull request #567
Opened 2024-05-14 03:25 UTC by SentryMan

Adds all the backwards compatibility stuff from #566 minus the SPI changes

2024-05-14 11:07 UTC, rbygrave approved these changes

2024-05-14 11:07 UTC, rbygrave commented on inject/src/test/java/io/avaje/inject/LegacyBeanScopeBuilderTest.java
> +  private static class TDModule implements AvajeModule {
My guess is that this should implement Module and not AvajeModule

2024-05-14 11:09 UTC, rbygrave requested changes
Need to resolve why InjectPlugin exists

2024-05-14 11:21 UTC, rbygrave commented
Did you hit this issue of desiring 10.x to be backwards compatible or did someone else?  Just wondering of the pain level. Also just to say I'm kind of not loving "AvajeModule" as a name ... so I'm hoping that something better might come to me.

2024-05-14 11:26 UTC, SentryMan commented
Yeah, I noticed that all the plugins and libraries I've made at work ceased to function

2024-05-14 11:27 UTC, SentryMan commented
> Need to resolve why InjectPlugin exists

The maven plugin/generator is unable to get the type array from legacy plugins.

2024-05-15 14:58 UTC, SentryMan commented
> don't like "AvajeModule" as a name 

I was thinking of `AvajeModule` sort of like Guice has `GuiceModule`.

I got a couple of alternate options (just spitballing here):

- BeanModule
- ScopeModule
- GraphModule
- WiringModule
- DependencyModule

2024-05-15 21:44 UTC, rob-bygrave commented
> AvajeModule sort of like Guice has GuiceModule

Yeah, that makes sense. IMO the original "Module" was a poor choice by me. "InjectModule" is taken by the annotation (which seems ok) ... so I'm definately warming to AvajeModule (it's mostly used internally).

I should get to review this again today. Great work by the way !!!

2024-05-16 09:34 UTC, merged